apiVersion: v1
entries:
  cloud-provider-azure:
  - apiVersion: v1
    created: "2022-05-23T08:58:32.805781125Z"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 333f935087f05bead79cb7c8d57285f324756599b86f4c1fc08aa19f006ae6d9
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.0+20220523.tgz
    version: 1.24.0+20220523
  - apiVersion: v1
    created: "2022-05-06T10:10:12.501287-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: c9aa0bf18ee1442f9ae57ae277a6a7b1c7b88f33836508a6a97fb593cd1e1750
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.0.tgz
    version: 1.24.0
  - apiVersion: v1
    created: "2022-05-02T14:33:56.285027-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: f65eb45cbf65e78e117e9dec98afd1ea0cc9ff8be878d263c3230fc2ea974429
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.11.tgz
    version: 1.23.11
  - apiVersion: v1
    created: "2022-04-19T10:36:40.02457-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 4d259c7900cf9ef5fb19418ec8728d3a67bc900a770b25ea6ea72fbb75726c19
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.10.tgz
    version: 1.23.10
  - apiVersion: v1
    created: "2022-03-29T19:24:38.168893-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 6e8c1d218845874e446dccf566ea18a09c06c9d2a766215eb7c5d9e2729be0be
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.8.tgz
    version: 1.23.8
generated: "2022-05-23T08:58:32.805017015Z"
