apiVersion: v1
entries:
  cloud-provider-azure:
  - apiVersion: v1
    created: "2022-08-02T10:08:16.841896+01:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 79f1258f2de7d9ab94a543e4b4db2fa606dc6e4d19352379db266f08964ffba9
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.4.tgz
    version: 1.24.4
  - apiVersion: v1
    created: "2022-07-13T09:05:30.19016+02:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: bc04fb728a3b218033557ccca6eabb846453af87986c6a0befd997840fa6efbe
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.3.tgz
    version: 1.24.3
  - apiVersion: v1
    created: "2022-06-20T12:15:28.687498+02:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 754588ada7519270fcfa04b2a14a232237f0b189812a1d577be5377709c6c5e4
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.2.tgz
    version: 1.24.2
  - apiVersion: v1
    created: "2022-06-08T10:09:42.766825-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 43a3aced346dbcaeec4e0b3e710c1f5b9aa7b4fc6a74e2b96e5f1bdb18fd1194
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.1.tgz
    version: 1.24.1
  - apiVersion: v1
    created: "2022-06-01T00:37:05.622970767Z"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: bdf7a959bdb4aa4452c11a58768d05b83864778e56f588c728e4e609311b59bd
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.0+20220601.tgz
    version: 1.24.0+20220601
  - apiVersion: v1
    created: "2022-05-26T13:57:34.35813407+02:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 90de09f45ccf3a379eb2959236244670ee0fbf66ecf9ec056c9b39050bf69646
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.0+20220526.tgz
    version: 1.24.0+20220526
  - apiVersion: v1
    created: "2022-05-06T10:10:12.501287-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: c9aa0bf18ee1442f9ae57ae277a6a7b1c7b88f33836508a6a97fb593cd1e1750
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.24.0.tgz
    version: 1.24.0
  - apiVersion: v1
    created: "2022-05-02T14:33:56.285027-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: f65eb45cbf65e78e117e9dec98afd1ea0cc9ff8be878d263c3230fc2ea974429
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.11.tgz
    version: 1.23.11
  - apiVersion: v1
    created: "2022-04-19T10:36:40.02457-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 4d259c7900cf9ef5fb19418ec8728d3a67bc900a770b25ea6ea72fbb75726c19
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.10.tgz
    version: 1.23.10
  - apiVersion: v1
    created: "2022-03-29T19:24:38.168893-07:00"
    description: A Helm chart for installing kubernetes-sigs/cloud-provider-azure
      components
    digest: 6e8c1d218845874e446dccf566ea18a09c06c9d2a766215eb7c5d9e2729be0be
    home: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/cloud-provider-azure/README.md
    keywords:
    - cloud-provider-azure
    - kubernetes-sigs
    - kubernetes
    maintainers:
    - email: jackfrancis@gmail.com
      name: Jack Francis
    - email: zhechengli1995@outlook.com
      name: Zhecheng Li
    name: cloud-provider-azure
    sources:
    - https://github.com/kubernetes-sigs/cloud-provider-azure
    urls:
    - cloud-provider-azure-1.23.8.tgz
    version: 1.23.8
generated: "2022-08-02T10:08:16.841139+01:00"
