name: kubetest2 release

on:
  workflow_dispatch:
  schedule:
    - cron: '* 0 * * 1'

permissions:
  contents: read
  packages: write

env:
  ARTIFACT: oci://ghcr.io/${{github.repository_owner}}/kubetest2-aks

jobs:
  build-kubetest2-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: kubetest2-aks/go.mod
      - name: Build binary
        run: |
          cd kubetest2-aks
          make deployer
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup kustomizer
        uses: stefanprodan/kustomizer/action@main
      - name: Push
        run: |
          kustomizer push artifact ${ARTIFACT}:${{ github.ref_name }} -f ./kubetest2-aks/bin/kubetest2-aks \
            --source=${{ github.repositoryUrl }} \
            --revision="${{ github.ref_name }}/${{ github.sha }}"
      - name: Tag latest
        run: |
          kustomizer tag artifact ${ARTIFACT}:${GITHUB_REF_NAME} latest